version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
  
  user-service-postgres:
    image: postgres:16
    container_name: user-service-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_service
    ports:
      - "5432:5432"
    volumes:
      - user_service_postgres_data:/var/lib/postgresql/data

volumes:
  user_service_postgres_data: